# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-13 17:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20211126_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incart', 'В корзине'), ('intransit', 'Доставляется'), ('delivered', 'Доставлен')], max_length=300, verbose_name='Статус')),
                ('total_price', models.IntegerField(default=0, verbose_name='Итоговая стоимость')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Orders',
                'ordering': ['holder'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название товара')),
                ('short', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Описание товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.CharField(choices=[('cat1', 'Фигурки'), ('cat2', 'Значки'), ('cat3', 'Постеры')], max_length=300, verbose_name='Категория')),
                ('image', models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'db_table': 'Goods',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость товаров')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Orders', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Shop', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары заказа',
                'db_table': 'SubOrders',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 13, 20, 49, 52, 359003), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 13, 20, 49, 52, 359003), verbose_name='Дата'),
        ),
    ]
